model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.GAN_ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: cond_image
    image_size: 32
    channels: 4
    concat_mode: True # False
    scale_by_std: false # False will set to 1

    cond_stage_trainable: false # True
    conditioning_key: concat
    monitor: val/loss_simple_ema
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8 # image, cond image
        out_channels: 4 # half of in
        model_channels: 32
        attention_resolutions: [ 1, 2, 4 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "logs/2024-03-07T13-26-17_autoencoder_kl_32x32x4_test/checkpoints/epoch=000484.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_first_stage__ # need this to specify cond key
#      target: ldm.modules.encoders.modules.SpatialRescaler

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 20
    num_workers: 4 ##
    wrap: False
    train:
      target: ldm.data.yztoxy.ZEnhanceTrain
      params:
        data_root: ["/home/meng-yun/Projects/rb_vessel/Dataset/vessel1_xy","/home/meng-yun/Projects/rb_vessel/Dataset/vessel1_xy_cyclow"]
        mask_config:
          direction: "horizontal"
          down_size: 8
        mode: train
    validation:
      target: ldm.data.yztoxy.ZEnhanceValidation
      params:
        data_root: ["/home/meng-yun/Projects/rb_vessel/Dataset/vessel1_xy","/home/meng-yun/Projects/rb_vessel/Dataset/vessel1_xy_cyclow"]
        mask_config:
          direction: "horizontal"
          down_size: 8
        mode: train

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        increase_log_steps: False


  trainer:
    max_epochs: 40000
    benchmark: True